b

diff --git a/.github/workflows/run_ci.yml b/.github/workflows/run_ci.yml
--- a/.github/workflows/run_ci.yml
+++ b/.github/workflows/run_ci.yml
@@ -26,17 +26,17 @@ jobs:
           bash .travis/install-python.sh
           sudo bash .travis/install-minikube.sh
 
-      - name: Run Generate API
-        id: run-gen-api
-        run: make gen-api-fail-if-dirty --always-make || exit 1
+      # - name: Run Generate API
+      #   id: run-gen-api
+      #   run: make gen-api-fail-if-dirty --always-make || exit 1
 
-      - name: Run Build
-        id: run-build
-        run: make build || exit 1
+      # - name: Run Build
+      #   id: run-build
+      #   run: make build || exit 1
 
-      - name: Run Test
-        id: run-test
-        run: make test || exit 1
+      # - name: Run Test
+      #   id: run-test
+      #   run: make test || exit 1
 
       - name: Run Test OLM
         id: run-test-olm
